### ISSUE TITLE
Improve tracery grammar

### ISSUE THREAD

**Issue by shiffman** [ITPNYU/ICMadness#2]
* Should it be possible for there to be one or more technologies? 
* Sometimes the phrasing is a bit awkward.

**Comment by shiffman** [comment]
@leoneckert It appears the slot machine doesn't use Tracery . . which is fine, we can remove it as a dependency! The grammar here is a really a simple madlibs. @aparrish do you have any thoughts? Are we missing out on some grammar ideas by simplifying to just three blank spots?

**Comment by aparrish** [comment]
I think there's a little bit of flexibility lost, but it's clearer this way how it works and I think the constraint will make us more creative in coming up with ideas about what to put in the slots!

**Comment by shiffman** [comment]
Great, I've removed the dependencies!
