### ISSUE TITLE
Design and Animation

### ISSUE THREAD

**Issue by shiffman** [ITPNYU/ICMadness#3]
No thought has been put into how this looks or behaves! https://itpnyu.github.io/ICMadness/

Slot machine? Roulette Wheel? What else to improve the visual design of the project generator page?

**Comment by leoneckert** [comment]
I am playing with this right now, will post updates!

**Comment by leoneckert** [comment]
@shiffman , I built something like this ( that is also still completely modifiable :) ), but can't push it (I guess because I am not part of @ITPNYU ? It works with the same random seed, permalink etc you put into place...
![screen shot 2017-10-23 at 6 36 15 pm](https://user-images.githubusercontent.com/14130931/31916547-33e46a38-b821-11e7-8b01-30f099d6197a.png)

**Comment by shiffman** [comment]
This is AMAZING. I'll add you as a collaborator so you can push directly. Excited to try it out.

**Comment by leoneckert** [comment]
@shiffman still cant push, I think you need to add residents team to the repo's settings? (this screenshot is from asome old repo that I do have now access to...)

<img width="434" alt="screen shot 2017-10-23 at 8 40 55 pm" src="https://user-images.githubusercontent.com/14130931/31919748-80083b22-b832-11e7-8ec2-b9edfa4b150f.png">

**Comment by shiffman** [comment]
Ooops, I had but left it as "read" access only. .  should be all set now!

**Comment by leoneckert** [comment]
it's up. if anyone has suggestion on styling it differently I am super open. Had mostly fun getting the mechanics of it to work 👍

**Comment by shiffman** [comment]
I love it! I wonder if with the permalink, it shouldn't spin? Although it is kind of fun to watch it go again. 

My random number seed way of generating the same project idea works, but I wonder if it's a bad idea given how it will immediately fail if the JSON data files ever change. I'll open a new issue to consider saving to firebase or something instead.

**Comment by kaganjd** [comment]
leon this is awesome!!

it seems like the instructions are different than what the slot machine shows. what if we just go with what the slot machine generates and show resources below?

<img width="1242" alt="screen shot 2017-10-24 at 12 51 49 pm" src="https://user-images.githubusercontent.com/9204835/31956546-bb5a7a78-b8b9-11e7-818b-70f88f5816cf.png">

**Comment by shiffman** [comment]
I reworked it a bit to remove the extra instructions at the top and place the resources list below the slot machine. I am going to open a new issue regarding tracking the final instructions and displaying the corresponding resources.
