### ISSUE TITLE
Associating resources with instructions

### ISSUE THREAD

**Issue by shiffman** [ITPNYU/ICMadness#9]
@leoneckert Can you help add something where the wheel object's return the text of their final selection? This way we can add back in the related resources below the canvas.

**Comment by leoneckert** [comment]
added it and appears again below the canvas - just needs styling :)

**Comment by leoneckert** [comment]
this is a link that returns an item with resources in case you wanna check or someone wants to style differently: [https://itpnyu.github.io/ICMadness/?id=1508882914864](https://itpnyu.github.io/ICMadness/?id=1508882914864)

**Comment by shiffman** [comment]
@leoneckert this pull request from @aparrish #11  had some conflicts with your recent changes, I resolved them but may have messed up some of the spacing if you want to double-check!

**Comment by meiamsome** [comment]
This appears to be working fine, except that all the entries in the current `resources.json` are missing the articles they have in `generator.json`.

**Comment by shiffman** [comment]
Awesome, I've added a whole bunch of resources and also a feature that removes the previous resources for each spin. It still needs some design help but I will close this issue for now!
